### ISSUE TITLE
500 Server Error: Internal Server Error for url: https://api.2k.com/borderlands/users/authenticate

### ISSUE THREAD

**Issue by sirjeannot** [derekn/blshift#1]
Hello,

since recently the tool returns the following error:
`Error: 500 Server Error: Internal Server Error for url: https://api.2k.com/borderlands/users/authenticate`
using version 1.8.4

My credentials work, the account isn't locked. Something may have changed on gearbox side.
Can this be resolved? :)

Thanks!

**Comment by derekn** [comment]
I've released an update for this, can you give it a try and let me know if it works for you

**Comment by sirjeannot** [comment]
Thank you and sorry for the delayed answer.
It does work but gets stuck on a specific key (CS5JB-CTTBB-FFWXZ-FJ3BT-TC6R3)
![image](https://github.com/derekn/blshift/assets/9054080/8f85e889-0e4c-41b6-889d-6e950f4f3746)
(I did clear the cache)

**Comment by derekn** [comment]
Error 429 indicates you're being rate-limited by the server, if you try it again after a period of time it should start working again.
