### ISSUE TITLE
Orcicorn is dead

### ISSUE THREAD

**Issue by Eddga** [derekn/blshift#2]
As [announced on the corresponding Twitter account](https://x.com/dgSHiFTCodes), the Shift Code bot and with him shift.orcicorn.com is dead since April 2023.
Therefore no new codes can be pulled automatically at the moment.
I don't know if there's a successor to it out there. I couldn't find one. :(

**Comment by Eddga** [comment]
I came across a seemingly abandoned repo that had the same issue:
https://github.com/Fabbi/autoshift/issues/53
This guy forked it and made it work again scraping codes from other sites (mentalmars.com):
https://github.com/ugoogalizer/autoshift
And he even continuously updates a github repo with his scraper:
https://github.com/ugoogalizer/autoshift-codes/
Maybe you can use this to fix blshift or just archive it and link to his repo.

**Comment by derekn** [comment]
thank you, I will archive this repo and link to the one provided.
